INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Notebook Dell Inspiron 15', 3899.00, 10, 4.2);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Smartphone Samsung Galaxy S23', 4599.00, 15, 4.8);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('iPhone 14 Pro Max', 7899.00, 8, 4.9);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Smart TV LG 55" 4K', 2799.00, 12, 3.9);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Console PlayStation 5', 3899.00, 6, 4.7);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Console Xbox Series X', 3799.00, 7, 4.5);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Cadeira Gamer ThunderX3', 1299.00, 20, 3.2);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Mouse Logitech MX Master 3', 499.00, 30, 4.9);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Teclado Mecânico Redragon Kumara', 299.00, 25, 3.8);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Monitor Gamer AOC 27" 144Hz', 1499.00, 14, 4.3);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('HD Externo Seagate 2TB', 549.00, 18, 3.5);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('SSD Kingston NV2 1TB NVMe', 379.00, 22, 4.6);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Placa de Vídeo RTX 4070 Ti', 4999.00, 5, 4.8);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Processador AMD Ryzen 7 5800X', 1899.00, 9, 4.4);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Placa-mãe ASUS TUF B550M', 1099.00, 11, 3.6);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Memória RAM Corsair 16GB DDR4', 299.00, 40, 4.1);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Fonte Corsair 650W 80 Plus Bronze', 499.00, 13, 2.9);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Gabinete Gamer NZXT H510', 599.00, 10, 4.0);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Headset HyperX Cloud II', 599.00, 21, 4.5);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Impressora HP DeskJet Ink Advantage', 449.00, 16, 2.8);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Kindle Paperwhite 11ª Geração', 699.00, 9, 4.7);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Câmera GoPro Hero 11', 2599.00, 7, 4.2);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Apple Watch Series 9', 4299.00, 8, 4.6);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Xiaomi Mi Band 8', 299.00, 25, 3.9);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Ar Condicionado LG Dual Inverter 12000 BTUs', 2299.00, 6, 4.3);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Geladeira Brastemp Frost Free 375L', 2999.00, 4, 3.7);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Máquina de Lavar Electrolux 11Kg', 2399.00, 5, 4.1);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Micro-ondas Panasonic 32L', 749.00, 12, 3.4);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Fogão 5 Bocas Consul Inox', 1899.00, 3, 2.7);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Cafeteira Nespresso Essenza Mini', 599.00, 18, 4.6);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Aspirador de Pó Robô Roomba i3', 2899.00, 4, 4.2);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Smart Speaker Amazon Echo Dot 5ª Geração', 379.00, 28, 4.8);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Caixa de Som JBL Charge 5', 899.00, 17, 4.4);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Violão Yamaha C40', 899.00, 8, 3.6);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Teclado Musical Casio CT-X700', 1399.00, 5, 3.9);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Bicicleta Caloi Elite Carbon', 7999.00, 2, 4.5);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Patinete Elétrico Xiaomi Mi Scooter 3', 2999.00, 6, 4.0);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Drone DJI Mini 3 Pro', 4699.00, 3, 4.7);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Relógio Casio G-Shock', 699.00, 14, 4.3);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Perfume Paco Rabanne 1 Million 100ml', 499.00, 20, 3.8);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Tênis Nike Air Max 270', 899.00, 19, 4.2);
INSERT INTO tb_product (name, price, stock, assessment) VALUES ('Notebook Apple MacBook Air M2', 10499.00, 5, 4.9);